'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")>  _
Partial Friend NotInheritable Class PluginSetting
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As PluginSetting = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New PluginSetting()),PluginSetting)
    
    Public Shared ReadOnly Property [Default]() As PluginSetting
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DataPath() As String
        Get
            Return CType(Me("DataPath"),String)
        End Get
        Set
            Me("DataPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DisabledPlugin() As String
        Get
            Return CType(Me("DisabledPlugin"),String)
        End Get
        Set
            Me("DisabledPlugin") = value
        End Set
    End Property
End Class
